// frontendAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css'],
})
export class ArticlesComponent implements OnInit {
  public url: string;
  @Input() articles: Article[];

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {}
}

<div class="loading" *ngIf="!articles">
  Cargando...
</div>

<div id="articles" *ngIf="articles">
  <article
    class="article-item"
    id="article-template"
    *ngFor="let article of articles"
  >
    <div class="image-wrap">
      <img
        src="{{ url + 'getImage/' + article.image }}"
        alt="{{ article.title }}"
        *ngIf="article.image"
      />
      <img
        src="../../../assets/images/no-imagen.jpg"
        alt="{{ article.title }}"
        *ngIf="!article.image"
      />
    </div>

    <h2>{{ article.title }}</h2>
    <span class="date">
      {{ article.date | amLocale: "es" | amTimeAgo }}
    </span>
    <a [routerLink]="['/blog/articulo', article._id]">Leer más</a>

    <div class="clearfix"></div>
  </article>

  <!--AÑADIR ARTICULOS VIA JS-->
</div>

// FrontendVue/src/components/Articles.vue
<template>
  <section>
    <div id="articlesList" v-if="articles && articles.length >= 1">
      <article
        class="article-item"
        id="article-template"
        v-for="article in articles"
        :key="article._id"
      >
        <div class="image-wrap">
          <img
            :src="url + 'getImage/' + article.image"
            :alt="article.title"
            v-if="article.image"
          />
          <img
            src="../assets/images/no-imagen.jpg"
            :alt="article.title"
            v-if="!article.image"
          />
        </div>
        <h2>{{ article.title }}</h2>
        <span class="date">
          {{ article.date }}
        </span>
        <a href="#">Leer más</a>
        <div class="clearfix"></div>
      </article>
    </div>
    <div v-else>
      <h1 class="subheader" style="color: #09a330">Cargando...</h1>
    </div>
  </section>
</template>

<script>
import Global from "../Global";
export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>

<style></style>
