// FrontendVue/src/components/views/Article.vue
<template>
  <div>
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap">
            <img
              :src="url + 'getImage/' + article.image"
              :alt="article.title"
              v-if="article.image"
            />
            <img
              src="../../assets/images/no-imagen.jpg"
              :alt="article.title"
              v-if="!article.image"
            />
          </div>

          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date">
            {{ article.date | moment("from", "now") }}
          </span>
          <p>
            {{ article.content }}
          </p>

          <div class="clearfix"></div>

          <router-link :to="'/editar/' + article._id" class="btn btn-warning"
            >Editar</router-link
          >
          <a @click="deleteArticle(article._id)" class="btn btn-danger"
            >Eliminar</a
          >
        </article>
      </section>
      <Sidebar />
    </div>
  </div>
</template>

<script>
import axios from "axios";
import Global from "../../Global";
import Sidebar from "../Sidebar.vue";
import swal from "sweetalert";
export default {
  name: "Article",
  components: {
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    this.getArticle(this.$route.params.id);
  },
  methods: {
    getArticle(articleId) {
      axios
        .get(this.url + "article/" + articleId)
        .then((res) => {
          if (res.data.status == "success") {
            this.article = res.data.article;
          }
        })
        .catch((err) => {
          console.log(err);
        });
    },
    deleteArticle(articleId) {
      swal({
        title: "Estás seguro?",
        text: "Una vez borrado el articulo, no se puede recuperar",
        icon: "warning",
        buttons: [true, true],
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          axios
            .delete(this.url + "article/" + articleId)
            .then((res) => {
              swal(
                "Articulo borrado",
                "El artículo se ha borrado exitosamente",
                "success"
              );
              this.$router.push("/blog");
            })
            .catch((err) => {
              swal("Error algo salió mal", err, "error");
            });
        } else {
          swal("No se ha borrado el artículo");
        }
      });
    },
  },
};
</script>

<style></style>

// frontendAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from '../../services/global';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import swal from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService],
})
export class ArticleComponent implements OnInit {
  public article: Article;
  public url: string;

  constructor(
    public _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe((params) => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        (response) => {
          if (response.article) {
            this.article = response.article;
          } else {
            this._router.navigate(['/home']);
          }
        },
        (error) => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      );
    });
  }

  delete(id) {
    swal({
      title: 'Estás seguro?',
      text: 'Una vez borrado el articulo, no se puede recuperar',
      icon: 'warning',
      buttons: [true, true],
      dangerMode: true,
    }).then((willDelete) => {
      if (willDelete) {
        this._articleService.delete(id).subscribe(
          (response) => {
            console.log(response);
            swal('El artículo ha sido borrado', {
              icon: 'success',
            });
            this._router.navigate(['/blog']);
          },
          (err) => {
            console.log(err);
            this._router.navigate(['/blog']);
          }
        );
      } else {
        swal('No se ha borrado el artículo');
      }
    });
  }
}

<div class="loading" *ngIf="!article">
  Cargando...
</div>

<div class="center" *ngIf="article">
  <section id="content">
    <article class="article-item article-detail">
      <div class="image-wrap">
        <img
          src="{{ url + 'getImage/' + article.image }}"
          alt="{{ article.title }}"
          *ngIf="article.image"
        />
        <img
          src="../../../assets/images/no-imagen.jpg"
          alt="{{ article.title }}"
          *ngIf="!article.image"
        />
      </div>

      <h1 class="subheader">{{ article.title }}</h1>
      <span class="date">
        {{ article.date | amLocale: "es" | amTimeAgo }}
      </span>
      <p>
        {{ article.content }}
      </p>
      <div class="buttons">
        <a [routerLink]="['/blog/editar/', article._id]" class="btn btn-warning"
          >editar</a
        >
        <a (click)="delete(article._id)" class="btn btn-danger">borrar</a>
      </div>

      <div class="clearfix"></div>
    </article>
  </section>
  <app-sidebar></app-sidebar>
</div>
